### ISSUE TITLE
Issues with running example

### ISSUE THREAD

**Issue by JamesPatrick1014** [Shathe/ML-Superpixels#1]
Great work on this method, but i'm having trouble executing the code you provided. When I try to generate augmented annotations, the line:

```python 
# Generate superpixels
os.system("sh generate_superpixels/generate_superpixels.sh " + args.dataset + size_sup_string)
``` 
throws this error for each iteration:

`generate_superpixels/generate_superpixels.sh: line 25: ./bin/cli: >> cannot execute binary file: Exec form`

Not too familiar with binaries myself, a quick [Google search](https://unix.stackexchange.com/questions/421049/troubleshooting-advice-for-bash-cannot-execute-binary-file-exec-format-error) says that because `cli` and all of the other files in `bin` were compiled on your unix-based machine, other machines with different architectures will not be able to execute those commands.

` cli: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32`

 Is it possible that you can provide the original source code for your SLIC implementation or binaries for other architectures? Thanks!

**Comment by Shathe** [comment]
Hi, 

I updated the readme for solving this problem:

First of all please, go to [this repository](https://github.com/davidstutz/superpixels-revisited), clone it, [install and compile it](https://github.com/davidstutz/superpixels-revisited#building) and replace the generated binaries in [this folder](https://github.com/Shathe/ML-Superpixels/tree/master/bin) (delete the folders inside ./bin of this repo and copy the folders generated in the superpixels-revisited repo).

**Comment by Shathe** [comment]
I am closing this, if the problem remains, please do not doubt to reopen it!: D

**Comment by JamesPatrick1014** [comment]
Hey @Shathe, if you're interested in including .exe versions for each of the over-segmentation algorithms in this repo, you can download them [here](https://we.tl/t-nqLs4T7pIK). Because they're .exe files, all of the necessary components are included so anyone running on Windows should be able to run them just fine. If you include them in the bin folder anyone using these would just need to change the first line of the .sh file so these are called instead.

They might need an additional .dll file (for example, tbb.dll), but that can be found and downloaded off the internet and included in the same folder as the .exe files, and/or in the Windows/System32 directory.

Hope this helps! (the link with the download expires in a few days)

**Comment by Shathe** [comment]
This is very cool! Thanks a lot for your contribution, I am adding them right now!!!!
